# Netlify configuration for RigShare Monorepo

# Operators App (Main/Default)
[build]
  command = "npm run build:operators"
  publish = "apps/operators/build"
  
# Environment variables (set in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Admin App Branch Deploy (optional)
[context.admin]
  command = "npm run build:admin"
  publish = "apps/admin/build"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"